apiVersion: apps/v1
kind: Deployment
metadata:
  name: bd-airports-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: bd-airports
  template:
    metadata:
      labels:
        app: bd-airports
    spec:
      containers:
      - name: bd-airports
        image: docker pull mukitmuntasir/bd-airports:latest
        ports:
        - containerPort: 8080
        resources:
          limits:
            memory: "512Mi"
            cpu: "500m"
          requests:
            memory: "256Mi"
            cpu: "250m"

---

apiVersion: v1
kind: Service
metadata:
  name: bd-airports-service
spec:
  selector:
    app: bd-airports
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: LoadBalancer

